spring:
  application:
    name: portal
  datasource:
   tomcat:
     initial-size: 2   
cloud:
   config:
     uri: ${DOCKER_HOST_IP}:8888
security:
 oauth2:
   resource:
     accessTokenUri: ${DOCKER_HOST_IP}:8090/oauth/check_token
     userAuthorizationUri: ${DOCKER_HOST_IP}:8090/oauth/authorize
     userInfoUri: ${DOCKER_HOST_IP}:8090/user
     jwt:
       keyUri: ${DOCKER_HOST_IP}:8090/oauth/token_key
server:
 port: 8003
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DOCKER_HOST_IP}:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: ${DOCKER_HOST_IP}:${server.port}
